<!DOCTYPE html>
<html lang="en-US">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Tekolio</title>
<link rel="stylesheet" href="tekolio.css">
</head>
<body>
<div id="img1">
    <div class="img1"></div>
    <div id="bgb">
        <div id="tekolio">
            <a class="tekolio" href="tekolio.html">tekolio</a>
        </div>
        <div>
            <a href="#grow">
                <div id="a1">Grow Your Business</div> 
            </a>
        </div>
        <div>
            <a href="#advantages">
                <div id="a2">Advantages</div> 
            </a>
        </div>
        <div>
            <a href="#how">
               <div id="a3">How it's done</div> 
            </a>
        </div>
        <div> 
           <a href="#get">
               <div id="a4">Get in touch</div>
           </a>
        </div>
        <div id="convert">Get Websites That Convert</div><br>
        <div id="sales">Increase Your Sales With Your Website</div>
        <div id="a6"> 
            <a href="#get1">
                <div id="a5">Get in touch</div>
            </a>
         </div>
    </div>
</div>
<br><br>
<div id="content1">
    <a id="grow">
    <div id="c1">Grow Your Business</div>
    </a>
    <br><br>
    <div id="d2">
        <div id="i2">
            <img src="img2.png" alt="" class="i2">
        </div>
        <div id="c2">
            <div class="c2-h2">Get Sales 24X7</div>
        <div class="c2-p">
            The best thing about technology is that it can work forever. You no longer need to turn down your customers because you are not available. Your website will still serve your leads while your apps will serve your clients
        </div>
        </div>
    </div>
    <div id="d3">
        <div id="i3">
            <img src="img3.png" alt="" class="i3">
        </div>
        <div id="c3">
            <h2 class="c3-h2">Save Your Time And Effort</h2>
        <p class="c3-p">
            You now no longer need to answer every phone call that asks about your business offerings and your working hours. The website tells everything they want to know. You thus can focus on stuff that is more important
        </p>
        </div>
    </div>
    <div id="d4">
        <div id="i4">
            <img src="img4.png" alt="" class="i4">
        </div>
        <div id="c4">
            <div class="c2-h2">Expand The Reach Of Your Business</div>
        <div class="c2-p">
            The entire world deserves your offerings. You can now do business with anyone across the globe with just a few clicks.
        </div>
        </div>
    </div>
    <div id="d5">
        <div id="i5">
            <img src="img5.png" alt="" class="i3">
        </div>
        <div id="c5">
            <div class="c5-h2">Business First Approach</div><br><br>
        <div class="c5-p">
            Your apps are completely customised and tailored to meet your brand’s reputation and requirements
        </div>
        </div>
    </div>
    <div id="d6">
        <div id="i6">
            <img src="img6.png" alt="" class="i6">
        </div>
        <div id="c6">
            <div class="c2-h2">Create A Brand Persona</div>
        <div class="c2-p">
            Interacts with customers to make them feel comfortable and create trust in your business
        </div>
        </div>
    </div>
    <div id="d7">
        <div id="i7">
            <img src="img7.png" alt="" class="i3">
        </div>
        <div id="c7">
            <h2 class="c3-h2">Customer Oriented Approach</h2>
        <p class="c3-p">
            You can grow only as much as your customers are happy. Make your customers feel at home with content and functionalities that resonates with them
        </p>
        </div>
    </div>
</div>
<div id="content2">
    <a id="advantages">
    <div id="l1">Leverage High End Technology</div>
    </a>
    <br><br><br><br><br><br>
    <div id="g">
        <div id="g1">
            <div id="i8">
                <img src="image8.png" alt="" class="i8">
            </div>
        </div>
        <div id="g2">
            <div id="c8">
                <h2 class="c8-h2">Extremely Scalable</h2>
                    <p class="c8-p">
                        No matter you have 100 customers or 100,000, your website and applications can handle them all gracefully
                    </p>
            </div>
        </div>
        <div id="g3">
            <div id="i9">
                <img src="image9.png" alt="" class="i9">
            </div>
        </div>
        <div id="g4">
            <div id="c9">
                <h2 class="c8-h2">Simply Intuitive</h2>
                    <p class="c8-p">
                        If it’s difficult to use, it’s actually useless. We ensure that anyone can use our products without much effort
                    </p>
            </div>
        </div>
        <div id="g5">
            <div id="i10">
                <img src="image10.png" alt="" class="i10">
            </div>
        </div>
        <div id="g6">
            <div id="c9">
                <h2 class="c8-h2">Payment Gateway</h2>
                    <p class="c8-p">
                        No matter how far your customer is, we ensure that he can pay you with a few clicks
                    </p>
            </div>
        </div>
        <div id="g7">
            <div id="i">
                <img src="image11.png" alt="" class="i8">
            </div>
        </div>
        <div id="g8">
            <div id="c8">
                <h2 class="c8-h2">Admin Panel</h2>
                    <p class="c8-p">
                        Get more insights into the workings of the applications using admin dashboards
                    </p>
            </div>
        </div>
        <div id="g9">
            <div id="i">
                <img src="image12.png" alt="" class="i9">
            </div>
        </div>
        <div id="g10">
            <div id="c8">
                <h2 class="c8-h2">Cloud Hosting</h2>
                    <p class="c8-p">
                        Leverage cloud to make the your website and apps available at all times
                    </p>
            </div>
        </div>
        <div id="g11">
            <div id="i">
                <img src="image13.png" alt="" class="i10">
            </div>
        </div>
        <div id="g12">
            <div id="c0">
                <h2 class="c8-h2">Secure</h2>
                    <p class="c8-p">
                        Security is the most critical element of anything online. We ensure that your apps and websites are secure so that your customers can trust you with their money
                    </p>
            </div>
        </div>
    </div>
</div>
<br><br><br><br>
<div id="content3">
    <a id="how">
        <div id="c1">How It's Done</div>
    </a>
    <br><br><br>
    <div id="whole">
        <div id="cir1" class="a1">1</div>
        <div id="con1">You contact us</div>
        <div id="cir" class="a2">2</div>
        <div id="con">We will then reach out to you and book a call with you as per your convenience</div>
        <div id="cir" class="a3">3</div>
        <div id="con">A series of calls will be conducted to ensure that we understand your business well</div>
        <div id="cir" class="a4">4</div>
        <div id="con">A proposal will be crafted to specifically meet your business needs</div>
        <div id="cir2" class="a5">5</div>
        <div id="con2">We'll work on the project</div>
        <div id="cir" class="a6">6</div>
        <div id="con">You get to see the end result and suggest some more improvements</div>
        <div id="cir" class="a7">7</div>
        <div id="con">You get a great product which boosts your sales and help you grow your business</div>
    </div>
    <div id="hr1"><hr></div>
    <div id="hr2"><hr></div>
   <div id="hr3"><hr></div>
    <div id="hr4"><hr></div>
    <div id="hr5"><hr></div>
    <div id="hr6"><hr></div>
</div>
<div id="footer">
    
</div>
</body>
